export const categData = [
  {label: 'Trauma and Stress Related Disorders', value: 'a'},
  {label: 'Somatic Symptom and Related Disorders', value: 'b'},
  {label: 'Sleep-Wake Disorders', value: 'c'},
  {label: 'Sexual Dysfunction', value: 'd'},
  {label: 'Schizophrenia Spectrum and Other Psychotic Disorders', value: 'e'},
  {label: 'Personality Disorders', value: 'f'},
  {label: 'Paraphilic Disorders', value: 'g'},
  {label: 'Obsessive-Compulsive and Related Disorders', value: 'h'},
  {label: 'Neurodevelopmental Disorders', value: 'i'},
  {label: 'Substance and Related Disorders', value: 'j'},
  {label: 'Anxiety', value: 'k'},
  {label: 'Bipolar', value: 'l'},
  {label: 'Disruptive', value: 'm'},
  {label: 'Depressive Disorder', value: 'n'},
  {label: 'Dissociative Disorders', value: 'o'},
  {label: 'Elimination Disorders', value: 'p'},
  {label: 'Feeding and Eating Disorders', value: 'q'},
  {label: 'Gender Dysphoria', value: 'r'},
  {label: 'Neurocognitive Disorders', value: 's'},
];
